### ISSUE TITLE
大佬，开启隧道后curl https://api.ip.sb/ip 会提示 CApath: none 但是实际*   CAfile: /etc/pki/tls/certs/ca-bundle.crt 路径没有错误

### ISSUE THREAD

**Issue by gkingt** [gngpp/vproxy#3]
![image](https://github.com/gngpp/vproxy/assets/137085967/6f6377c5-a27d-4f16-a0b0-b5eb82fb892e)
请问是什么原因，应该怎么解决

**Comment by gngpp** [comment]
这就不知道了 既然都走隧道了，这事不关代理的事了

**Comment by gngpp** [comment]
你跑文档写的example能不能用就知道了，这个API没有指定UA会被拦掉

**Comment by gkingt** [comment]
我再研究研究，谢谢大佬
