### ISSUE TITLE
Socks5 proxy ?

### ISSUE THREAD

**Issue by maxirmx** [gngpp/vproxy#8]
Hello and thank you for the great tool !

It looks like socks5 proxy is just stubbed. Do you have any plans to implement it ?

Thank you

**Comment by gngpp** [comment]
Yes, I plan to implement socks5 proxy, but first I have to implement https proxy

**Comment by maxirmx** [comment]
If I implement socks5 would you consider a PR ?

**Comment by gngpp** [comment]
Absolutely!👏
